fix(doc): fix incorrect values for `formatType` (#807)
### Motivation

The value options of `formatType` are incorrect. It will throw the following exception :
```
java.lang.RuntimeException: not support formatType Avro
```
The value should be all lowercase. Such as `json`, `avro`.

### Modifications

- Fix incorrect values for `formatType`

(cherry picked from commit 6437d1ec8dbcfcb55f67ec9e88443186e1c0c9c3)